CREATE USER feten WITH PASSWORD 'Am8e72Vb';
REVOKE CONNECT ON DATABASE l49 FROM PUBLIC;

GRANT CONNECT
ON DATABASE l49 
TO feten;

REVOKE ALL
ON ALL TABLES IN SCHEMA coordination 
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA coordination 
TO feten;

ALTER DEFAULT PRIVILEGES IN SCHEMA coordination
  GRANT SELECT, INSERT, UPDATE, DELETE ON tables TO feten;

ALTER DEFAULT PRIVILEGES IN SCHEMA coordination
  GRANT SELECT, USAGE ON sequences TO feten;