CREATE ROLE l49;
CREATE ROLE riyad LOGIN IN GROUP l49;
GRANT  CONNECT ON DATABASE l49  TO riyad;
--REVOKE CONNECT ON DATABASE l49 FROM riyad;
GRANT SELECT ON ALL TABLES IN SCHEMA  administratif  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA administratif FROM riyad ;
GRANT SELECT ON ALL TABLES IN SCHEMA  coordination  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA coordination FROM riyad ;
GRANT SELECT ON ALL TABLES IN SCHEMA  erdf  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA erdf FROM riyad ;
GRANT SELECT ON ALL TABLES IN SCHEMA  orange  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA orange FROM riyad ;
GRANT SELECT ON ALL TABLES IN SCHEMA  rip1  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA rip1 FROM riyad ;
GRANT SELECT ON ALL TABLES IN SCHEMA  rip2  TO riyad ;
--REVOKE ALL ON ALL TABLES IN SCHEMA rip2 FROM riyad ;


