/*GraceTHD v2-RC2*/
/*Insertion des valeurs dans les listes de valeurs*/
/*PostGIS*/
SET search_path TO optimisation_diag, public;

BEGIN;
INSERT INTO l_avancement VALUES ('E', 'EXISTANT', '');
INSERT INTO l_avancement VALUES ('C', 'A CREER', '');
INSERT INTO l_avancement VALUES ('T', 'TRAVAUX', '');
INSERT INTO l_avancement VALUES ('S', 'EN SERVICE', '');
INSERT INTO l_avancement VALUES ('H', 'HORS SERVICE', '');
INSERT INTO l_avancement VALUES ('A', 'ABANDONNE', '');
INSERT INTO l_clim_type VALUES ('SANS', 'SANS', '');
INSERT INTO l_clim_type VALUES ('VENTIL', 'VENTILLATION', '');
INSERT INTO l_clim_type VALUES ('CLIM', 'CLIMATISATION', '');
INSERT INTO l_etat_type VALUES ('HS', 'A CHANGER', 'L infrastructure doit etre changee car la moindre intervention peut etre prejudiciable a la fourniture du service');
INSERT INTO l_etat_type VALUES ('ME', 'MAUVAIS ETAT', 'Mauvais etat general de l infrastructure qui ne permet pas certaines interventions');
INSERT INTO l_etat_type VALUES ('OK', 'BON ETAT', 'Bon etat general qui permet de realiser toute operation de maintenance, d exploitation ou d evolution');
INSERT INTO l_etat_type VALUES ('NC', 'NON CONCERNE', '');
INSERT INTO l_geoloc_classe VALUES ('A', 'Classe de précision A', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe A si l incertitude maximale de localisation indiquée par son exploitant est inférieure ou égale à 40 cm et s il est rigide, ou à 50 cm s il est flexible. ');
INSERT INTO l_geoloc_classe VALUES ('AP', 'Classe de précision A, en planimétrie uniquement', 'Idem classe A, mais uniquement pour les valeurs x et y (hors z)');
INSERT INTO l_geoloc_classe VALUES ('B', 'Classe de précision B', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe B si l incertitude maximale de localisation indiquée par son exploitant est supérieure à celle relative à la classe A et inférieure ou égale à 1,5 mètre.');
INSERT INTO l_geoloc_classe VALUES ('C', 'Classe de précision C', 'Décret du 15 février 2012 : un ouvrage ou tronçon d ouvrage est rangé dans la classe C si l incertitude maximale de localisation indiquée par son exploitant est supérieure à 1,5 mètre, ou si son exploitant n est pas en mesure de fournir la localisation.');
INSERT INTO l_geoloc_mode VALUES ('LTRO', 'LEVE DURANT LA POSE', 'Objet positionne grace à un leve durant la phase travaux. Dans le cas de tranchee, ce leve a ete realise tranchee ouverte.');
INSERT INTO l_geoloc_mode VALUES ('LVIS', 'LEVE APRES LA POSE', 'Objet positionne grace a un leve. Dans le cas d une tranchee, uniquement les elements visibles ont ete leves (rustines sur le revetement, chambres encadrantes). Des cotations prises pendant la pose ont permis de completer ce lever.');
INSERT INTO l_geoloc_mode VALUES ('DETC', 'LEVE AVEC DETECTION', 'Un appareil de detection a ete utilise pour positionner les elements à lever.');
INSERT INTO l_geoloc_mode VALUES ('FDPL', 'COTATION PAR RAPPORT A UN LEVE DE GEOMETRE', 'Objet implante en reportant des cotations prises par rapport à un fond de plan precedemment leve.');
INSERT INTO l_geoloc_mode VALUES ('CBDU', 'COTATION PAR RAPPORT A UN FOND DE PLAN TIERS TYPE BDU', 'Objet implante en reportant des cotations prises par rapport au meilleur fond de plan actuellement disponible.');
INSERT INTO l_geoloc_mode VALUES ('CADA', 'POSITIONNEMENT SUR CADASTRE', 'Objet positionne par rapport aux planches cadastrales.');
INSERT INTO l_geoloc_mode VALUES ('ORTO', 'POSITIONNEMENT SUR ORTHOPHOTOGRAPHIE OU FOND DE PLAN CARTOGRAPHIQUE', 'Objet positionne par rapport à des orthophotos, ou des fonds cartographiques type RGE, FRANCE RASTER, OSM ou Bing');
INSERT INTO l_geoloc_mode VALUES ('INDT', 'INDETERMINE', '');
INSERT INTO l_immeuble_type VALUES ('P', 'PAVILLON', '');
INSERT INTO l_immeuble_type VALUES ('I', 'IMMEUBLE', '');
INSERT INTO l_implantation_type VALUES ('0', 'AERIEN TELECOM', '');
INSERT INTO l_implantation_type VALUES ('1', 'AERIEN ENERGIE', '');
INSERT INTO l_implantation_type VALUES ('2', 'FACADE', '');
INSERT INTO l_implantation_type VALUES ('3', 'IMMEUBLE', '');
INSERT INTO l_implantation_type VALUES ('4', 'PLEINE TERRE', '');
INSERT INTO l_implantation_type VALUES ('5', 'CANIVEAU', '');
INSERT INTO l_implantation_type VALUES ('6', 'GALERIE', '');
INSERT INTO l_implantation_type VALUES ('7', 'CONDUITE', '');
INSERT INTO l_implantation_type VALUES ('8', 'EGOUT', '');
INSERT INTO l_implantation_type VALUES ('9', 'SPECIFIQUE', '');
INSERT INTO l_infra_type_log VALUES ('CX', 'COLLECTE TRANSPORT DISTRIBUTION', '');
INSERT INTO l_infra_type_log VALUES ('CO', 'COLLECTE', 'Infrastructures en amont d’un NRO, d un NRA ou d un POP, permettant de faire transiter les flux mutualises des abonnes vers le cœur de reseau de l operateur.');
INSERT INTO l_infra_type_log VALUES ('CT', 'COLLECTE TRANSPORT', '');
INSERT INTO l_infra_type_log VALUES ('CD', 'COLLECTE DISTRIBUTION', '');
INSERT INTO l_infra_type_log VALUES ('TD', 'TRANSPORT DISTRIBUTION', 'Mutualisation des fonctions transport et distribution');
INSERT INTO l_infra_type_log VALUES ('TR', 'TRANSPORT', 'Infrastructure situee entre un noeud de raccordement (NRO, NRA, …) et les sous-repartiteurs (SRO, ...). ');
INSERT INTO l_infra_type_log VALUES ('DI', 'DISTRIBUTION', 'Infrastructure situee entre le sous-repartiteur (SRO, ...) et les points de branchement (PBO, ...). ');
INSERT INTO l_infra_type_log VALUES ('RA', 'RACCORDEMENT FINAL', 'Infrastructure  situee  entre  le  point de branchement (PBO, ...) et la prise terminale (DTIO, ...). ');
INSERT INTO l_infra_type_log VALUES ('BM', 'BOUCLE METROPOLITAINE', '');
INSERT INTO l_infra_type_log VALUES ('LH', 'LONGUE DISTANCE (LONG HAUL)', '');
INSERT INTO l_infra_type_log VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_passage_type VALUES ('ACC', 'ACCOTEMENT', '');
INSERT INTO l_passage_type VALUES ('CHAU', 'CHAUSSEE', '');
INSERT INTO l_passage_type VALUES ('TROT', 'TROTTOIR', '');
INSERT INTO l_passage_type VALUES ('TER', 'TERRE', '');
INSERT INTO l_passage_type VALUES ('EMP', 'EMPIERRE', '');
INSERT INTO l_passage_type VALUES ('PON', 'PONT', '');
INSERT INTO l_passage_type VALUES ('SNC', 'PASSAGE SNCF', '');
INSERT INTO l_passage_type VALUES ('CAN', 'CANIVEAU TECHNIQUE', '');
INSERT INTO l_passage_type VALUES ('PAV', 'PAVES', '');
INSERT INTO l_passage_type VALUES ('AQU', 'AQUATIQUE', '');
INSERT INTO l_passage_type VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_pose_type VALUES ('NC', 'NON COMMUNIQUE', '');
INSERT INTO l_pose_type VALUES ('TRA', 'TRADITIONNELLE', '');
INSERT INTO l_pose_type VALUES ('MEC', 'MECANISEE', '');
INSERT INTO l_pose_type VALUES ('MIC', 'MICRO TRANCHEE', '');
INSERT INTO l_pose_type VALUES ('FOR', 'FORAGE DIRIGE', '');
INSERT INTO l_pose_type VALUES ('ENS', 'ENSOUILLAGE', '');
INSERT INTO l_pose_type VALUES ('FON', 'FONÇAGE', '');
INSERT INTO l_pose_type VALUES ('ENC', 'ENCORBELLEMENT', '');
INSERT INTO l_pose_type VALUES ('STU', 'SOUS-TUBAGE', 'Sous-tubage infra existante');
INSERT INTO l_priorite VALUES ('1', '1', 'Programmation du local technique en priorité 1');
INSERT INTO l_priorite VALUES ('2', '2', 'Programmation du local technique en priorité 2');
INSERT INTO l_priorite VALUES ('3', '3', 'Programmation du local technique en priorité 3');
INSERT INTO l_propriete_type VALUES ('CST', 'CONSTRUCTION', '');
INSERT INTO l_propriete_type VALUES ('RAC', 'RACHAT', '');
INSERT INTO l_propriete_type VALUES ('CES', 'CESSION', '');
INSERT INTO l_propriete_type VALUES ('IRU', 'IRU', '');
INSERT INTO l_propriete_type VALUES ('LOC', 'LOCATION', '');
INSERT INTO l_propriete_type VALUES ('OCC', 'OCCUPATION', 'Convention d occupation');
INSERT INTO l_ptech_nature VALUES ('A1', 'CHAMBRE A1', '');
INSERT INTO l_ptech_nature VALUES ('A2', 'CHAMBRE A2', '');
INSERT INTO l_ptech_nature VALUES ('A3', 'CHAMBRE A3', '');
INSERT INTO l_ptech_nature VALUES ('A4', 'CHAMBRE A4', '');
INSERT INTO l_ptech_nature VALUES ('B1', 'CHAMBRE B1', '');
INSERT INTO l_ptech_nature VALUES ('B2', 'CHAMBRE B2', '');
INSERT INTO l_ptech_nature VALUES ('B3', 'CHAMBRE B3', '');
INSERT INTO l_ptech_nature VALUES ('B4', 'CHAMBRE B4', '');
INSERT INTO l_ptech_nature VALUES ('C1', 'CHAMBRE C1', '');
INSERT INTO l_ptech_nature VALUES ('C2', 'CHAMBRE C2', '');
INSERT INTO l_ptech_nature VALUES ('C3', 'CHAMBRE C3', '');
INSERT INTO l_ptech_nature VALUES ('C4', 'CHAMBRE C4', '');
INSERT INTO l_ptech_nature VALUES ('D1', 'CHAMBRE D1', '');
INSERT INTO l_ptech_nature VALUES ('D2', 'CHAMBRE D2', '');
INSERT INTO l_ptech_nature VALUES ('D3', 'CHAMBRE D3', '');
INSERT INTO l_ptech_nature VALUES ('D4', 'CHAMBRE D4', '');
INSERT INTO l_ptech_nature VALUES ('E1', 'CHAMBRE E1', '');
INSERT INTO l_ptech_nature VALUES ('E2', 'CHAMBRE E2', '');
INSERT INTO l_ptech_nature VALUES ('E3', 'CHAMBRE E3', '');
INSERT INTO l_ptech_nature VALUES ('E4', 'CHAMBRE E4', '');
INSERT INTO l_ptech_nature VALUES ('J2C', 'CHAMBRE J2C', '');
INSERT INTO l_ptech_nature VALUES ('J2CR', 'CHAMBRE J2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K1C', 'CHAMBRE K1C', '');
INSERT INTO l_ptech_nature VALUES ('K1CR', 'CHAMBRE K1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K2C', 'CHAMBRE K2C', '');
INSERT INTO l_ptech_nature VALUES ('K2CR', 'CHAMBRE K2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('K3C', 'CHAMBRE K3C', '');
INSERT INTO l_ptech_nature VALUES ('K3CR', 'CHAMBRE K3C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L0T', 'CHAMBRE L0T', '');
INSERT INTO l_ptech_nature VALUES ('L0TR', 'CHAMBRE L0T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L1C', 'CHAMBRE L1C', '');
INSERT INTO l_ptech_nature VALUES ('L1T', 'CHAMBRE L1T', '');
INSERT INTO l_ptech_nature VALUES ('L1TR', 'CHAMBRE L1T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L2C', 'CHAMBRE L2C', '');
INSERT INTO l_ptech_nature VALUES ('L2T', 'CHAMBRE L2T', '');
INSERT INTO l_ptech_nature VALUES ('L2TR', 'CHAMBRE L2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L3C', 'CHAMBRE L3C', '');
INSERT INTO l_ptech_nature VALUES ('L3T', 'CHAMBRE L3T', '');
INSERT INTO l_ptech_nature VALUES ('L3TR', 'CHAMBRE L3T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L4C', 'CHAMBRE L4C', '');
INSERT INTO l_ptech_nature VALUES ('L4T', 'CHAMBRE L4T', '');
INSERT INTO l_ptech_nature VALUES ('L4TR', 'CHAMBRE L4T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L5C', 'CHAMBRE L5C', '');
INSERT INTO l_ptech_nature VALUES ('L5T', 'CHAMBRE L5T', '');
INSERT INTO l_ptech_nature VALUES ('L5TR', 'CHAMBRE L5T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('L6T', 'CHAMBRE L6T', '');
INSERT INTO l_ptech_nature VALUES ('L6TR', 'CHAMBRE L6T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M1C', 'CHAMBRE M1C', '');
INSERT INTO l_ptech_nature VALUES ('M1CR', 'CHAMBRE M1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M2T', 'CHAMBRE M2T', '');
INSERT INTO l_ptech_nature VALUES ('M2TR', 'CHAMBRE M2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('M3C', 'CHAMBRE M3C', '');
INSERT INTO l_ptech_nature VALUES ('M3CR', 'CHAMBRE M3C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P1C', 'CHAMBRE P1C', '');
INSERT INTO l_ptech_nature VALUES ('P1CR', 'CHAMBRE P1C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P1T', 'CHAMBRE P1T', '');
INSERT INTO l_ptech_nature VALUES ('P1TR', 'CHAMBRE P1T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P2C', 'CHAMBRE P2C', '');
INSERT INTO l_ptech_nature VALUES ('P2CR', 'CHAMBRE P2C REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('P2T', 'CHAMBRE P2T', '');
INSERT INTO l_ptech_nature VALUES ('P2TR', 'CHAMBRE P2T REHAUSSEE', '');
INSERT INTO l_ptech_nature VALUES ('PBOI', 'POTEAU BOIS', '');
INSERT INTO l_ptech_nature VALUES ('PBET', 'POTEAU BETON', '');
INSERT INTO l_ptech_nature VALUES ('PMET', 'POTEAU METAL', '');
INSERT INTO l_ptech_nature VALUES ('PIND', 'POTEAU INDETERMINE', '');
INSERT INTO l_ptech_nature VALUES ('POTL', 'POTELET', '');
INSERT INTO l_ptech_nature VALUES ('R1T', 'CHAMBRE R1T', '');
INSERT INTO l_ptech_nature VALUES ('R2T', 'CHAMBRE R2T', '');
INSERT INTO l_ptech_nature VALUES ('R3T', 'CHAMBRE R3T', '');
INSERT INTO l_ptech_nature VALUES ('BOU', 'BOUCHON', '');
INSERT INTO l_ptech_nature VALUES ('REG', 'REGARD 30X30', '');
INSERT INTO l_ptech_nature VALUES ('OHN', 'OUVRAGE HORS NORMES', '');
INSERT INTO l_ptech_nature VALUES ('TRA', 'TRAVERSE', '');
INSERT INTO l_ptech_nature VALUES ('CRO', 'CROCHET', '');
INSERT INTO l_ptech_nature VALUES ('BAL', 'BALCON', '');
INSERT INTO l_ptech_nature VALUES ('FAI', 'FAITIERE', '');
INSERT INTO l_ptech_nature VALUES ('STR', 'SOUTERRAIN', '');
INSERT INTO l_ptech_nature VALUES ('SSO', 'SOUS-SOL', '');
INSERT INTO l_ptech_nature VALUES ('Y', 'SITE MANCHONNAGE Y', 'Fenêtre ouverture sur fourreaux existant pour mise en Y');
INSERT INTO l_ptech_nature VALUES ('IND', 'INDETERMINE', '');
INSERT INTO l_site_type_log VALUES ('NRA', 'NŒUD RACCORDEMENT D ABONNES', '');
INSERT INTO l_site_type_log VALUES ('NRAHD', 'NŒUD RACCORDEMENT D ABONNES - HAUT DEBIT', '');
INSERT INTO l_site_type_log VALUES ('NRAMED', 'NŒUD RACCORDEMENT D ABONNES - MONTEE EN DEBIT', '');
INSERT INTO l_site_type_log VALUES ('NRAZO', 'NŒUD RACCORDEMENT D ABONNES - ZONE D OMBRE', '');
INSERT INTO l_site_type_log VALUES ('SRP', 'SOUS-REPARTITEUR CUIVRE PRIMAIRE', '');
INSERT INTO l_site_type_log VALUES ('SRS', 'SOUS-REPARTITEUR CUIVRE SECONDAIRE', '');
INSERT INTO l_site_type_log VALUES ('SRT', 'SOUS-REPARTITEUR CUIVRE TERTIAIRE', '');
INSERT INTO l_site_type_log VALUES ('NRO', 'NŒUD RACCORDEMENT OPTIQUE', '');
INSERT INTO l_site_type_log VALUES ('SRO', 'SOUS-REPARTITEUR OPTIQUE', '');
INSERT INTO l_site_type_log VALUES ('SROL', 'SOUS-REPARTITEUR OPTIQUE COLOCALISE', 'Sous-repartiteur localise dans le NRO. ');
INSERT INTO l_site_type_log VALUES ('BRASSAGE', 'SITE DE BRASSAGE', 'Site non prevu pour heberger des equipements actifs (surtout longue distance)');
INSERT INTO l_site_type_log VALUES ('CLIENT', 'SITE CLIENT', 'Site entreprise ou administration qui n est pas un site utilisateur final (SUF). ');
INSERT INTO l_site_type_log VALUES ('HEBERG', 'SITE HEBERGEMENT', 'Site d hebergement d equipements actifs qui n est pas un NRO (hors architecture FTTH). ');
INSERT INTO l_site_type_phy VALUES ('ADR', 'ARMOIRE DE RUE', '');
INSERT INTO l_site_type_phy VALUES ('BAT', 'BATIMENT', '');
INSERT INTO l_site_type_phy VALUES ('COF', 'COFFRET', 'Notamment coffrets qui peuvent etre fixes sur des appuis et qui font office d armoires. ');
INSERT INTO l_site_type_phy VALUES ('SHE', 'SHELTER', '');
INSERT INTO l_version VALUES ('V1', 'V1', 'Version étude préliminaire 1 du diagnositc de réseau');
INSERT INTO l_version VALUES ('V2', 'V2', 'Version étude préliminaire 2 du diagnositc de réseau');
INSERT INTO l_version VALUES ('V3', 'V3', 'Version étude préliminaire 3 du diagnositc de réseau');
COMMIT;
